- hosts: localhost
  vars_files:
    - vars/global.yaml
    - vars/ssh.yaml
    - vars/xenv.yaml
    - vars/docker.yaml
  pre_tasks:
    - name: Update APT
      become: true
      apt:
        force_apt_get: true
        update_cache: true
      tags:
        - ubuntu
        - wsl
  tasks:
    - include: tasks/1.ssh.yml
    - include: tasks/2.git.yml
    - include: tasks/3.xenv.yml
    - include: tasks/4.apt.yml
    - include: tasks/5.npm-packages.yml
    - include: tasks/6.zsh.yml
    - include: tasks/7.nvim.yml
    - include: tasks/8.dotfiles.yml
