- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    nvm_path: ".nvm"
    nvm_version: "0.39.0"
    nvm_versions:
      - 18.1.0
    goenv_path: ".goenv"
    goenv_version: "0.0.5"
    goenv_versions:
      - 1.18.0
    pyenv_path: ".pyenv"
    pyenv_versions:
      - 3.10.5
  pre_tasks:
    - name: Update APT
      become: true
      apt:
        force_apt_get: true
        update_cache: true
      tags:
        - ubuntu
        - wsl
        - mac
  tasks:
    - include: tasks/1.ssh.yml
    - include: tasks/2.git.yml
    - include: tasks/3.xenv.yml
    - include: tasks/4.apt.yml
    - include: tasks/5.npm-packages.yml
    - include: tasks/6.zsh.yml
    - include: tasks/7.nvim.yml
