- name: (Node Env) - Check if nvm is installed.
  stat:
    path: "{{ lookup('env', 'HOME') }}/{{ nvm_path }}"
  register: ndir
  tags: &all_tags [ 'ubuntu', 'wsl' ]

- name: (Node Env) - Installing nvm.
  when: ndir.stat.isdir is not defined
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash
  args:
    creates: "{{ lookup('env', 'HOME') }}/{{ nvm_path }}/nvm.sh"
  tags: *all_tags

- name: (Node Env) - setting up nvm.
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - 'export NVM_DIR="$HOME/{{ nvm_path }}"'
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
  tags: *all_tags

- name: (Node Env) - Install latest node.
  shell: . {{ lookup('env', 'HOME') }}/.bashrc && nvm install "{{ item }}"
  with_items: "{{ nvm_versions }}"
  tags: *all_tags

- name: (GO Env) - Check if goenv is installed.
  stat:
    path: "{{ lookup('env', 'HOME') }}/{{ goenv_path }}"
  register: gdir
  tags: *all_tags

- name: (GO Env) - Downloading goenv.
  when: gdir.stat.isdir is not defined
  git:
    repo: https://github.com/wfarr/goenv.git
    dest: "{{ lookup('env', 'HOME') }}/{{ goenv_path }}"
  tags: *all_tags

- name: (GO Env) - Create versions directory.
  file:
    path: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ goenv_path }}/versions"
  tags: *all_tags

- name: (GO Env) - setting up goenv.
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bashrc" 
    line: "{{ item }}"
  with_items:
    - 'export GOENV_ROOT="$HOME/{{ goenv_path }}"'
    - 'export PATH="$GOENV_ROOT/bin:$PATH"'
    - 'eval "$(goenv init -)"'
    - 'export PATH="$GOROOT/bin:$PATH"'
    - 'export PATH="$PATH:$GOPATH/bin"'
    - 'export GO111MODULE=on'
  tags: *all_tags

- name: (GO Env) - check installed versions.
  shell:
    ls {{ lookup('env', 'HOME') }}/{{ goenv_path }}/versions
  register: installed_nodes_go
  tags: *all_tags

- set_fact:
    nodes_go: "{{ goenv_versions | difference(installed_nodes_go.stdout_lines) }}"
  tags: *all_tags

- name: (GO Env) - install versions {{ nodes_go }}.
  shell:
    ~/{{ goenv_path }}/bin/goenv install "{{ item }}"
  with_items: "{{ nodes_go }}"
  when: nodes_go | length | int > 0
  tags: *all_tags

- name: (GO Env) - set global version to {{ goenv_versions | max }}.
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/{{ goenv_path }}/version"
    line: "{{ goenv_versions | max }}"
    state: present
    create: yes
  tags: *all_tags

- name: (Py Env) - Check if py is installed.
  stat:
    path: "{{ lookup('env', 'HOME') }}/{{ pyenv_path }}"
  register: pdir
  tags: *all_tags

- name: (Py Env) - downloading pyenv.
  when: pdir.stat.isdir is not defined
  shell: >
    curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  tags: *all_tags

- name: (Py Env) - Create versions directory.
  file:
    path: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ pyenv_path }}/versions"
  tags: *all_tags

- name: (Py Env) - Setting up pyenv.
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bashrc" 
    line: "{{ item }}"
  with_items:
    - 'export PATH="$HOME/{{ pyenv_path }}/bin:$PATH"'
    - 'eval "$(pyenv init --path)"'
    - 'eval "$(pyenv virtualenv-init -)"'
  tags: *all_tags

- name: (Py Env) - check installed versions.
  shell:
    ls {{ lookup('env', 'HOME') }}/{{ pyenv_path }}/versions
  register: installed_nodes_py
  tags: *all_tags

- set_fact:
    nodes_py: "{{ pyenv_versions | difference(installed_nodes_py.stdout_lines) }}"
  tags: *all_tags

- name: (Py Env) - install versions {{ nodes_py }}.
  shell:
    ~/{{ pyenv_path }}/bin/pyenv install "{{ item }}"
  with_items: "{{ nodes_py }}"
  when: nodes_py | length | int > 0
  tags: *all_tags

- name: (GO Env) - set global version to {{ pyenv_versions | max }}.
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/{{ pyenv_path }}/version"
    line: "{{ pyenv_versions | max }}"
    state: present
    create: yes
  tags: *all_tags

- name: (XEnv) - Restarting shell.
  shell: >
    exec $SHELL
  tags: *all_tags
