- name: (. files) - Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:mabn17/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags: &all_tags [ 'ubuntu', 'wsl', 'mac' ]

- name: (. files) - Stow dotfiles
  shell: cd $HOME/.dotfiles && ./all
  tags: *all_tags