- name: (. files) - Cloning .dotfiles.
  ansible.builtin.git:
    repo: 'git@github.com:mabn17/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - ubuntu
    - wsl
    - mac

- name: (. files) - Stow dotfiles for wsl.
  shell: cd $HOME/.dotfiles && ./wsl
  tags:
    - wsl

- name: (. files) - Stow dotfiles for mac.
  shell: cd $HOME/.dotfiles && ./mac
  tags:
    - mac

- name: (. files) - Stow dotfiles for ubuntu.
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - ubuntu
